[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
# This ensures native binaries for Linux are downloaded
cmds = ["npm install --platform=linux --arch=x64"]

[phases.build]
cmds = ["npm run build"]
