[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
# Force removal of any existing node_modules before installing
cmds = ["rm -rf node_modules", "npm install --include=optional"]

[phases.build]
cmds = ["npm run build"]
